# Generated by sergonj on Tue Dec  9 12:00:01 AM MSK 2025
/ip firewall address-list
add list=Cloudflare address=173.245.48.0/20 comment=Cloudflare
add list=Cloudflare address=103.21.244.0/22 comment=Cloudflare
add list=Cloudflare address=103.22.200.0/22 comment=Cloudflare
add list=Cloudflare address=103.31.4.0/22 comment=Cloudflare
add list=Cloudflare address=141.101.64.0/18 comment=Cloudflare
add list=Cloudflare address=108.162.192.0/18 comment=Cloudflare
add list=Cloudflare address=190.93.240.0/20 comment=Cloudflare
add list=Cloudflare address=188.114.96.0/20 comment=Cloudflare
add list=Cloudflare address=197.234.240.0/22 comment=Cloudflare
add list=Cloudflare address=198.41.128.0/17 comment=Cloudflare
add list=Cloudflare address=162.158.0.0/15 comment=Cloudflare
add list=Cloudflare address=104.16.0.0/13 comment=Cloudflare
add list=Cloudflare address=104.24.0.0/14 comment=Cloudflare
add list=Cloudflare address=172.64.0.0/13 comment=Cloudflare
add list=Cloudflare address=131.0.72.0/22 comment=Cloudflare
